# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.1
- 3.2
- oldrel
- release
- devel

addons:
  apt:
    packages:
      - python3

before_install:
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install numpy todotxtio
  #- sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
  - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - testthat
   - reticulate

after_success:
  - Rscript -e 'covr::codecov()'
