# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.1
- 3.2
- oldrel
- release
- devel

addons:
  apt:
    packages:
      - python3

before_install:
  - pip install numpy todotxtio

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - testthat
   - reticulate

after_success:
  - Rscript -e 'covr::codecov()'
